# Generated by Django 3.2.3 on 2021-05-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to='event_images/')),
                ('blog_text', models.CharField(max_length=300)),
                ('blog_title', models.CharField(max_length=300)),
                ('blog_date', models.DateTimeField(default=None)),
            ],
        ),
    ]
